DROP TABLE SFIA_LEVELS;

SET SCAN OFF;

CREATE TABLE SFIA_LEVELS(
  LEVEL_NUMBER NUMBER(5),
  TITLE VARCHAR2(256),
  CONSTRAINT TABLE_SFIA_LEVELS_PK PRIMARY KEY (LEVEL_NUMBER)
);

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '1', 'follow'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '2', 'assist'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '3', 'apply'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '4', 'enable'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '5', 'ensure, advise'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '6', 'initiate, influence'  );

INSERT INTO SFIA_LEVELS (LEVEL_NUMBER, TITLE) VALUES ( '7', 'set strategy, inspire, mobilise'  );


commit;