DROP TABLE SFIA_LEVEL_CRITERIA;

SET SCAN OFF;

CREATE TABLE SFIA_LEVEL_CRITERIA(
  SFIA_LEVEL_CRITERIA_ID NUMBER(5),
  SFIA_LEVEL_CRITERIA_NAME VARCHAR2(256)
);

INSERT INTO SFIA_LEVEL_CRITERIA (SFIA_LEVEL_CRITERIA_ID, SFIA_LEVEL_CRITERIA_NAME) VALUES ( '1', 'Autonomy'  );

INSERT INTO SFIA_LEVEL_CRITERIA (SFIA_LEVEL_CRITERIA_ID, SFIA_LEVEL_CRITERIA_NAME) VALUES ( '2', 'Influence'  );

INSERT INTO SFIA_LEVEL_CRITERIA (SFIA_LEVEL_CRITERIA_ID, SFIA_LEVEL_CRITERIA_NAME) VALUES ( '3', 'Complexity'  );

INSERT INTO SFIA_LEVEL_CRITERIA (SFIA_LEVEL_CRITERIA_ID, SFIA_LEVEL_CRITERIA_NAME) VALUES ( '4', 'Business Skills'  );


commit;