drop table role;

set scan off;

create table ROLE(
  ROLENAME VARCHAR2(120) NOT NULL,
  ACTIVE VARCHAR2(5) NOT NULL,
  DESCRIPTION CLOB,
  CONSTRAINT TABLE_ROLE_PK PRIMARY KEY (ROLENAME)
);

ALTER TABLE ROLE ADD CONSTRAINT active_bool CHECK 
(
 ACTIVE IN('true','false')
);

INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'PDM CONSULTANT', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'PROJECT MANAGER', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'BUSINESS ANALYST', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'SUPPORT TECHNICIAN', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'SUPPORT ANALYST', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'SYSTEM ARCHITECT', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'DELIVERY MANAGER', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'SUPPORT MANAGER', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'SALES MANAGER', 'true' );
INSERT INTO ROLE (ROLENAME, ACTIVE ) VALUES ( 'STRATEGIC ANALYST', 'true' );

