
set scan off;

DROP TABLE USER_SKILL_BASELINE;
DROP TABLE USER_SKILL_BASELINE_ITEM;

# Represents a set of rows that show a user's baseline of skills at a certain point in time 

create table USER_SKILL_BASELINE(
  USER_BASELINE_ID NUMBER(9) NOT NULL,
  BASELINE_NAME VARCHAR2(256) NOT NULL,
  USER_ID VARCHAR2(120) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  LATEST VARCHAR2(1) NOT NULL,
  DESCRIPTION CLOB,
  CONSTRAINT TABLE_USER_SKILL_BL_PK PRIMARY KEY ( USER_ID, BASELINE_NAME, USER_BASELINE_ID )
);

create table USER_SKILL_BASELINE_ITEM(
  USER_BASELINE_ID NUMBER(9) NOT NULL,
  SKILL_ID VARCHAR2(10) NOT NULL,
  LEVEL_NUMBER NUMBER(5) NOT NULL,
  CONSTRAINT TABLE_USER_SKILL_BL_ITEM_PK PRIMARY KEY ( USER_BASELINE_ID, SKILL_ID, LEVEL_NUMBER )
);

INSERT INTO USER_SKILL_BASELINE( USER_BASELINE_ID, BASELINE_NAME, USER_ID, CREATION_DATE, LATEST, DESCRIPTION)
VALUES ( '1','January2006','train01',timestamp'2006-01-01 09:00:00.123456789','Y','Train01 my first baseline');

# level 5 architect
INSERT INTO USER_SKILL_BASELINE_ITEM(USER_BASELINE_ID, SKILL_ID, LEVEL_NUMBER) VALUES
('1', 'ARCH','5');
# Level 5 Software process improvement
INSERT INTO USER_SKILL_BASELINE_ITEM(USER_BASELINE_ID, SKILL_ID, LEVEL_NUMBER) VALUES
('1', 'SPIM','5');
