drop table ROLE_LEVEL;

set scan off;

create table ROLE_LEVEL (
  ROLENAME VARCHAR2(120) NOT NULL,
  ROLE_LEVEL NUMBER(5) NOT NULL,
  MIN_SALARY NUMBER(9,2),
  MAX_SALARY NUMBER(9,2),
  DESCRIPTION CLOB,
  CONSTRAINT TABLE_ROLE_LEVEL_PK PRIMARY KEY ( ROLENAME, ROLE_LEVEL )
);

INSERT INTO ROLE_LEVEL (ROLENAME, ROLE_LEVEL,MIN_SALARY,MAX_SALARY, DESCRIPTION)
VALUES ( 'PDM CONSULTANT','1','37000','45000','GRADUATE LEVEL PDM CONSULTANT / ANALYST');

INSERT INTO ROLE_LEVEL (ROLENAME, ROLE_LEVEL,MIN_SALARY,MAX_SALARY, DESCRIPTION)
VALUES ( 'PDM CONSULTANT','2','45000','60000','JUNIOR LEVEL PDM CONSULTANT/ANALYST. 2-3 years experience.');

INSERT INTO ROLE_LEVEL (ROLENAME, ROLE_LEVEL,MIN_SALARY,MAX_SALARY, DESCRIPTION)
VALUES ( 'PDM CONSULTANT','3','60000','80000','INTERMEDIATE LEVEL PDM CONSULTANT / ANALYST');

INSERT INTO ROLE_LEVEL (ROLENAME, ROLE_LEVEL,MIN_SALARY,MAX_SALARY, DESCRIPTION)
VALUES ( 'PDM CONSULTANT','4','81000','95000','SENIOR PDM CONSULTANT / ANALYST');
